create or replace FUNCTION F_BUSCAR_EMPLEADO(P_EMPLEADO IN EMPLEADOS.ID%TYPE)
  RETURN VARCHAR2 IS
  VNOMBRE EMPLEADOS.NOMBRE%TYPE;
BEGIN
  BEGIN
    SELECT NOMBRE
      INTO VNOMBRE
      FROM EMPLEADOS
     WHERE ID = P_EMPLEADO;
  EXCEPTION
    WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20001,
                              'OCURRIO UN ERROR AL OBTENER EL NOMBRE DEL CURSO - ' ||
                              SQLCODE || ' -ERROR- ' || SQLERRM);
  END;
  RETURN VNOMBRE;
END F_BUSCAR_EMPLEADO;